### ISSUE TITLE
Provide a filter above the grid for filename

### ISSUE THREAD

**Issue by accasey** [cy2hq/PeopleSoft-Directory-Viewer#11]
**Is your feature request related to a problem? Please describe.**
There can be many files in the LOGS directory, e.g. APPSRV_MMDD.LOG, TUXLOG.MMDDYY.
These all just get in the way of what you may want to look for which, as a developer, are most likely the *.tracesql files.

**Describe the solution you'd like**
I could see it in two ways:
1. Have a general text box at the top where you can enter a pattern, e.g. tracesql or APPSRV
2. Have some predefined types, e.g. tracesql or APPSRV, which you can select in a dropdown.

These would then be used to filter the list of files shown.

**Describe alternatives you've considered**
You can use the search to look for something, but it just finds the first file.
You can download the grid data and use Excel to filter, but it just becomes more time consuming.

**Additional context**
n/a

**Comment by ernstlahaye** [comment]
Filter option created for the directory viewer. Choose a prefix, pattern or extension value to filter by that value. When no results are found a message is shown and you can choose a different value. Once the grid is filtered the icon changes to indicate its filtered and when you click the button again, the filter is removed to show the original grid contents.
