### ISSUE TITLE
Logging of actions

### ISSUE THREAD

**Issue by accasey** [cy2hq/PeopleSoft-Directory-Viewer#13]
**Is your feature request related to a problem? Please describe.**
This is not in relation to any existing issue, at least not that I am aware of.

**Describe the solution you'd like**
When users use the 'Actions' button to do non-navigation related functions, e.g. upload a file, delete a file, create a directory, view a file etc. it would be useful to have the ability to record a log of these things for audit purposes and to know who did what and when.

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by ernstlahaye** [comment]
we created 3 options for audit logging: All actions, view actions and impact actions. These are set in the installation page for the directory viewer.
