### ISSUE TITLE
Hook into 'My Preferences' 

### ISSUE THREAD

**Issue by accasey** [cy2hq/PeopleSoft-Directory-Viewer#14]
**Is your feature request related to a problem? Please describe.**
This is not really related to a problem, but it would be useful to have some personalisations/preferences for this page.

**Describe the solution you'd like**
It would be nice that if you navigate to 'My Preferences' (Fluid page) there is an option to set the default Domain/Server.

**Describe alternatives you've considered**
The other solution I guess would be to consider different Permission Lists (as that is where this is defined) but this could get a little tedious.

**Additional context**
n/a

**Comment by ernstlahaye** [comment]
Hi Andrew, 

Just wanted to let you know we finally finished your request. We now have a preferences page in the "my preferences section" that allows the user to set:
- default domain + server 
- choose a permission list in case you have multiple permission lists that are in use in the directory viewer (handy for testing). 
- set default sort option for directories
- possibility to hide files < XXX kb size 

![image](https://user-images.githubusercontent.com/36766137/210095712-73055d0c-30ce-44e2-af19-80f7f71370c2.jpeg)

**Comment by accasey** [comment]
Hi @ernstlahaye thanks for the many changes of late. Have you integrated the changes into Github? I didn't see any new commits or releases.. Happy New Year by the way!
