### ISSUE TITLE
Would it be possible to upload more than one file at a time?

### ISSUE THREAD

**Issue by dbridg3** [cy2hq/PeopleSoft-Directory-Viewer#16]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by ernstlahaye** [comment]
That is a cool idea actually :). I am not sure if PeopleTools supports this....let me have a look.

**Comment by ernstlahaye** [comment]
Hi dbridg3. 

Just to let you know, we have finally picked up the project again and your enhancement has been built in. Turns out there is a nice Mass upload option in PeopleCode.
