### ISSUE TITLE
Tablespace for CY2_PSS_DIR_FLE does not exist

### ISSUE THREAD

**Issue by accasey** [cy2hq/PeopleSoft-Directory-Viewer#2]
I am guessing this is a Campus Solutions tablespace. I am installing this in our FSCM demo database.
Switching it to PTTBL (as per CY2_PSS_DIR_PDM) resolved the issue.

Error: CY2_PSS_DIR_FLE - SQL Error. Error Position: 229  Return: 959 - ORA-00959: tablespace 'SRAPP' does not exist
 
CREATE TABLE PS_CY2_PSS_DIR_FLE (CLASSID VARCHAR2(30) NOT NULL,    CY2_FILEEXTN VARCHAR2(30) NOT NULL,    CY2_CANNOT_VIEW VARCHAR2(1) NOT NULL,    CY2_CANNOT_UPLOAD VARCHAR2(1) NOT NULL,    CY2_CANNOT_DELETE VARCHAR2(1) NOT NULL) TABLESPACE SRAPP STORAGE (INITIAL 40000 NEXT 100000 MAXEXTENTS UNLIMITED PCTINCREASE 0) PCTFREE 10 PCTUSED 80

**Comment by ernstlahaye** [comment]
Hi @accasey, thanks for mentioning, completely forgot to check that for all tables. Will change it asap and upload new version to github.

**Comment by accasey** [comment]
No worries, not a big deal.. :-)

**Comment by ernstlahaye** [comment]
New version fixed issue.
