### ISSUE TITLE
Missing LastModifiedFileComparator in 8.59

### ISSUE THREAD

**Issue by iversond** [cy2hq/PeopleSoft-Directory-Viewer#21]
In a new PeopleTools 8.59.03 environment, we cannot open the Viewer page. On the page load, we are presented with a message saying the LastModifiedFileComparator class cannot be found.

```
Java Exception: java.lang.NoClassDefFoundError: org/apache/commons/io/comparator/LastModifiedFileComparator: finding class org.apache.commons.io.comparator.LastModifiedFileComparator
CY2_PSS_DIR.DirectoryViewer.OnExecute  Name:UpdateRowset  PCPC:2871  Statement:61
Called from:CY2_PSS_DIR.Components.CY2_PSS_DIR_VIEW.OnExecute  Name:PreBuild  Statement:22
Called from:CY2_PSS_DIR_VW_FL.GBL.PreBuild  Statement:2
```

**To Reproduce**
1. Click on the `PS servers directory view` Content Reference
2. The page will not load and present you with the error

**Expected behavior**
The page should load without an error. 

**Desktop (please complete the following information):**
 - OS: macOS 11.0
 - Browser: Safari
 - Version: 14.1

**Additional context**
This is our first time trying the tool on a new 8.59 environment. We will also file an SR with Oracle to see if they removed a library that contained that class.

**Comment by ernstlahaye** [comment]
Thanks Dan for letting us know, we are looking into it on our side. Had not used 8.59 ourselves as well with the viewer. Keep you posted and interested to hear what Oracle support comes back with as well....

Kind regards,
Ernst

**Comment by iversond** [comment]
Do you know what Java library this was included with in pre-8.59? We are comparing the libraries between 8.58 and 8.59 and the `commons` library is still included.

**Comment by ernstlahaye** [comment]
Hi Dan, 

We did look and the missing library (which we miss as well so its not your deployment) is: commons-io which is a jar. 
We also have worked on a simpler fix that just does the sorting based on peoplecode instead of using Java. But if you are allowed, adding that jar would probably do the trick as well. But not sure why Oracle removed it and if there is a side effect so perhaps better to add it to the custom jar directory.

Will keep you updated on our solution for the greater audience as well. Would rather not have to deliver jar files with our viewer, too much hassle :).

Kind regards,
ernst

**Comment by iversond** [comment]
That sounds like a good plan to remove the Java dependency. I think the switch to JDK 11 changed a few things in the standard libraries.

As a workaround, I downloaded the `commons-io` library and placed it under `$PS_HOME/class`. I then updated the `psappsrv.cfg` file with added:

```
Add to CLASSPATH=$PS_HOME/class
```

Reconfigured the domain and I was able to load the Directory Viewer page.

**Comment by iversond** [comment]
Heard back from Oracle Support, the `commons-io` library was removed for security reasons, so it won't be included from now on. So, if you do have a non-Java solution, that would be good. Otherwise we can download the library and include it ourselves.

**Comment by ernstlahaye** [comment]
Hi Dan, 

We are finally back to this project, we built a broader sorting option that allows users to sort by a number of options (including lastupdateddatetime).
