### ISSUE TITLE
Subpage is missing

### ISSUE THREAD

**Issue by accasey** [cy2hq/PeopleSoft-Directory-Viewer#3]
It looks like a Fluid subpage (SCC_CONFIRM_MSG_SBF) is missing

When I navigate to the 'PS servers directory view' page I get an error:
_Subpage SCC_CONFRM_MSG_SBF not found._

_The specified subpage does not exist in the database._
![subpage-missing](https://user-images.githubusercontent.com/25512664/108751526-3f91ba00-753a-11eb-940e-b0b32665f0d2.png)

**Comment by accasey** [comment]
Could not add record SCC_LO_FL_WRK for page CY2_PSS_DIR_VW_FL. Make sure record exists and does not contain corrupt data. 

The named page has one or more fields defined to use the named record, but the record definition could not be loaded. Make sure the record definition exists and does not contain corrupt data or change the page field(s) to use different record field(s).

**Comment by accasey** [comment]
There seems to be quite a few dependencies on CS (I think).
e.g. there is a group box using the following record/field on CY2_PSS_DIR_VW_FL:
* SCC_LO_FL_WRK.SCC_PAGE_TITLE_50


The App Packages are also quite dependent on the SCC_FLUID package.

**Comment by ernstlahaye** [comment]
Hi @accasey sorry for being my beta-tester it seems :(.Going to fix things now, please watch the github update which will arrive very soon....

**Comment by ernstlahaye** [comment]
all 3 issues to be fixed in version arriving 23-02-2021.

**Comment by nerdlett0608** [comment]
Yep, appeared dependent on some CS SCC% entities where FL was concerned. THANK YOU! I can avoid having to slip the offending items back into HCM.

**Comment by cuda** [comment]
Fixed in [v1.1](/cy2hq/PeopleSoft-Directory-Viewer/releases/tag/v1.1)
