### ISSUE TITLE
CY2_PSS_DIR_DHD does not exist

### ISSUE THREAD

**Issue by kbens** [cy2hq/PeopleSoft-Directory-Viewer#32]
Seems to be a minor cleanup thing, but Ver 2 project has Record.CY2_PSS_DIR_DHD in it but doesn't seem to exist after Copy From File?

![image](https://github.com/cy2hq/PeopleSoft-Directory-Viewer/assets/3799667/1b7c89ea-a51f-4d89-b1fb-b1e0f52964b7)

**Comment by ernstlahaye** [comment]
Hi Kyle, 

Thanks for the comments. Did you see my notes in the installation document for this version? Page 7 states this:

When building the tables in the project you may encounter warnings that correspond to the fields you have deleted as part of the upgrade. Those are expected. 

![image](https://github.com/cy2hq/PeopleSoft-Directory-Viewer/assets/36766137/97c48004-789e-4406-a96e-66e6011accab)

In the next version, I will remove the record from the project but I was not sure if people implemented 1.1 (or just version 1) so it was delivered as a "delete" for people who were still on version 1. 

Kind regards,
Ernst

**Comment by kbens** [comment]
RTFM - thanks, Ernst 👍
