### ISSUE TITLE
Cannot Create New PeopleSoft Server Permission List

### ISSUE THREAD

**Issue by bigdanallen** [cy2hq/PeopleSoft-Directory-Viewer#4]
Hi There,

On component: 'CY2_PSS_DIR_SETUP', you cannot create a brand new associated permission-list with run control record: 'CY2_PSS_DIR_PHD'.
I believe this is because you are requiring a Table Edit on field: CLASSID, which forces a prompt button, hence trying to validate even if you have clicked on 'Add a New Value'.

Also, I am in HCM, so record: 'SCC_LO_FL_WRK' doe snot exist for us. But I think you know about this issue already!

Great project mate, well done sir!

Cheers,

Dan Allen

**Comment by ernstlahaye** [comment]
HI @bigdanallen, 

I think the manual may not be clear enough, the idea is that the setup allows you to set server directory permissions for people based on an existing permission list. You can create a brand new permission list without any other content, choose that in "add a new valuue" and then link permissions to directories to that. That is the intended way of working and at least for me that works. If you see issues in this, please do let me know with a screenprint or 2 perhaps? 

The record issues will be resolved with the new version that is coming out today. Simply did not think of that part well enough. 

And thanks you like it :). 

Kind regards,
Ernst


![image](https://user-images.githubusercontent.com/36766137/108809575-718e3500-75a9-11eb-980a-20e1379fd001.png)

**Comment by ernstlahaye** [comment]
![image](https://user-images.githubusercontent.com/36766137/108809614-8cf94000-75a9-11eb-9af2-cb4e87883400.png)

**Comment by cuda** [comment]
Fixed in [v1.1](/cy2hq/PeopleSoft-Directory-Viewer/releases/tag/v1.1)
