### ISSUE TITLE
Missing HTML

### ISSUE THREAD

**Issue by accasey** [cy2hq/PeopleSoft-Directory-Viewer#5]
When I navigated to the following folder:
/u01/app/oracle/product/pt/ps_cfg_home/webserv/WEBSERVER01/applications/peoplesoft/PSIGW.war/WEB-INF

And I click the Action for the integrationGateway.properties file I receive an error straight away.
![use-of-action](https://user-images.githubusercontent.com/25512664/109145198-16e80b00-775a-11eb-8f78-473e198946fe.png)

If you look at the PeopleCode it uses HTML objects
![missing-html](https://user-images.githubusercontent.com/25512664/109145230-22d3cd00-775a-11eb-979c-bdf52d7ceff7.png)

But I don't seem to have any in my project.

**Comment by cuda** [comment]
fixed in [v1.2](/cy2hq/PeopleSoft-Directory-Viewer/releases/tag/v1.2)
