### ISSUE TITLE
add a default sorting option

### ISSUE THREAD

**Issue by cuda** [cy2hq/PeopleSoft-Directory-Viewer#6]

**Comment by ernstlahaye** [comment]
Make sure we Include the sorting option that was added at the end of the method UpdateRowset into the sorting logic.

**Comment by ernstlahaye** [comment]
Sorting options added to the installation, the personal preferences and the grid header. The default sort is based on installation, overridden by preferences and can be overridden by the user based on the sorting in the grid header.
