### ISSUE TITLE
Documenting Date Format Adjustments in the applicable Pcode for Last Modified on grid display

### ISSUE THREAD

**Issue by nerdlett0608** [cy2hq/PeopleSoft-Directory-Viewer#8]
I noticed the way the date was displaying and dug into the CY_LAST_MODIFIED treatment, which is in the Pcode in the App Package CY2_DSS_DIR (the DirectoryViewer application class).

So I adjusted as follows, which my comment here is to update the Technical and Install documentation to easily do this as a setup step after appyling the objects to your environment.

Local JavaObject &dateFormatter = CreateJavaObject("java.text.SimpleDateFormat", "**MM/dd**/yyyy HH:mm:ss"); where the original supplied was dd/MM.

Us'ns in the US typically display in the order above (whether slashes or dashes as separators, or spelling out the month, etc.)

Thanks!

**Comment by ernstlahaye** [comment]
Changed the value for CY2_LAST_MODIED to follow the logic as used in the DateTimeToUserFormat function. Which means it will first check the user preferences, then the browser locale settings if no preferences are set to determine how to visualize the last date time modified.
