### ISSUE TITLE
Provide a switch to not show 0 byte sized files

### ISSUE THREAD

**Issue by accasey** [cy2hq/PeopleSoft-Directory-Viewer#9]
**Is your feature request related to a problem? Please describe.**
We have some directories with many 'attachment.nnnn' files which I would like to be able to ignore.
For example I have 568 rows and I am sure the vast majority are these files.
So ideally I would like to be able not see them.

**Describe the solution you'd like**
Maybe either on optional filter (like the one for excluding file extensions) or just a flag (checkbox) that says 'Ignore Empty Files'

**Describe alternatives you've considered**
The only other thing I could think of was sorting the File/Directory column, but this meets mixed responses and does not really provide the full solution.

**Additional context**
n/a

**Comment by ernstlahaye** [comment]
Installation value + user defined preference value created for minimal file size to be shown. If the file size is smaller then the threshold value the file is not shown. 
Next to this, we are providing a filter option to hide certain types of files from the directory when you are viewing the directory.
